In [22]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"] = (20,10)


In [29]:
df = pd.read_csv('E:data_set1.csv',encoding='latin-1')
df.head()



day   customer_id               product_type  \
0  01/01/22  5.440000e+12  Maternity and Nursing Top   
1  01/01/22  5.730000e+12                   Baby Oil   
2  01/01/22  5.730000e+12                        NaN   
3  01/01/22  5.730000e+12       Baby Anti-Slip Socks   
4  01/01/22  5.770000e+12                        NaN   

                                       product_title shipping_city  \
0  Rose Melange Maternity and Feeding Sweatshirt ...       Panipat   
1  100% Natural Cold Pressed Virgin Coconut Oil f...       Gurgaon   
2                                                NaN       Gurgaon   
3  Socks with a Soul Combo - Baby Polar Bear & Sw...       Gurgaon   
4                                                NaN     Ghaziabad   

  shipping_region  orders  gross_sales  discounts  returns  net_sales  \
0         Haryana       1      1439.83    -316.76      0.0    1123.07   
1         Haryana       1       422.03     -42.20      0.0     379.83   
2         Haryana       0         0.00       0.00      0.0       0.00   
3         Haryana       1       677.12     -67.71      0.0     609.41   
4   Uttar Pradesh       0         0.00       0.00      0.0       0.00   

   shipping  duties  additional_fees   taxes  total_sales  \
0         0       0                0  202.15      1325.22   
1         0       0                0   68.37       448.20   
2         0       0                0    0.00         0.00   
3         0       0                0  109.69       719.10   
4         0       0                0    0.00         0.00   

   ordered_item_quantity  
0                      1  
1                      1  
2                      0  
3                      1  
4                      0

In [31]:
df.shape

(83356, 17)

In [32]:
df.groupby('product_type')['product_type'].agg('count')

product_type
Activity Seat            16
Adult Mask                5
After Sun Cream          12
Baby Activity Toys       42
Baby Anti-Slip Socks    379
                       ... 
Wipe Case                 6
Women Pajama Set        355
Wooden Horse              8
Wooden Horsey             2
Wooden Toys              88
Name: product_type, Length: 304, dtype: int64

In [34]:
df2= df.drop(['day','product_title','shipping_city','discounts','returns','shipping','duties','additional_fees','taxes'],axis='columns')
df2.head()

customer_id               product_type shipping_region  orders  \
0  5.440000e+12  Maternity and Nursing Top         Haryana       1   
1  5.730000e+12                   Baby Oil         Haryana       1   
2  5.730000e+12                        NaN         Haryana       0   
3  5.730000e+12       Baby Anti-Slip Socks         Haryana       1   
4  5.770000e+12                        NaN   Uttar Pradesh       0   

   gross_sales  net_sales  total_sales  ordered_item_quantity  
0      1439.83    1123.07      1325.22                      1  
1       422.03     379.83       448.20                      1  
2         0.00       0.00         0.00                      0  
3       677.12     609.41       719.10                      1  
4         0.00       0.00         0.00                      0

In [35]:
df2.isnull().sum()

customer_id                  0
product_type             33036
shipping_region            408
orders                       0
gross_sales                  0
net_sales                    0
total_sales                  0
ordered_item_quantity        0
dtype: int64

In [36]:
df3 = df2.dropna()
df3.isnull().sum()

customer_id              0
product_type             0
shipping_region          0
orders                   0
gross_sales              0
net_sales                0
total_sales              0
ordered_item_quantity    0
dtype: int64

In [37]:
df3.shape

(49984, 8)

In [39]:
df3['customer_id'].unique()

#to check how many unique customer id's are present

array([5.44e+12, 5.73e+12, 5.77e+12, 5.70e+12, 5.47e+12, 5.46e+12,
       4.56e+12, 5.33e+12, 5.37e+12, 5.43e+12, 5.12e+12, 5.63e+12,
       1.35e+12, 5.54e+12, 5.20e+12, 4.64e+12, 3.33e+12, 5.57e+12,
       2.14e+12, 5.69e+12, 4.57e+12, 5.38e+12, 5.78e+12, 2.10e+12,
       5.71e+12, 4.67e+12, 4.50e+12, 5.53e+12, 5.10e+12, 3.38e+12,
       4.35e+12, 5.67e+12, 5.72e+12, 4.40e+12, 5.76e+12, 2.75e+12,
       2.83e+12, 4.61e+12, 5.51e+12, 5.55e+12, 5.34e+12, 4.62e+12,
       5.75e+12, 5.22e+12, 5.66e+12, 5.36e+12, 2.93e+12, 5.13e+12,
       3.29e+12, 5.39e+12, 5.40e+12, 2.18e+12, 5.32e+12, 3.21e+12,
       5.11e+12, 3.22e+12, 5.65e+12, 3.41e+12, 4.63e+12, 5.68e+12,
       5.31e+12, 2.78e+12, 5.52e+12, 5.14e+12, 3.36e+12, 2.74e+12,
       2.70e+12, 5.16e+12, 2.07e+12, 2.89e+12, 3.05e+12, 2.65e+12,
       4.49e+12, 5.25e+12, 4.66e+12, 5.56e+12, 5.64e+12, 5.59e+12,
       5.49e+12, 5.74e+12, 5.07e+12, 2.97e+12, 3.03e+12, 5.28e+12,
       5.26e+12, 5.35e+12, 5.29e+12, 3.30e+12, 3.19e+12, 3.17e

In [40]:
df3['orders'].unique()

array([1, 2, 0, 3, 5, 4], dtype=int64)

In [41]:
df3['total_sales'].unique()

array([1325.22,  448.2 ,  719.1 , ..., 1415.2 ,  996.  , 3596.  ])

In [42]:
#there are values in ranges in the gross_sales,net_sales,total_sales columns, to handle those we will introduce a function to see how many values are there like this.

def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

In [44]:
df3[~df3['total_sales'].apply(is_float)]
#this will return true but for seeing the value we will use ~ ( this is negate operation.)

Empty DataFrame
Columns: [customer_id, product_type, shipping_region, orders, gross_sales, net_sales, total_sales, ordered_item_quantity]
Index: []

In [45]:
df3[~df3['total_sales'].apply(is_float)].head()

Empty DataFrame
Columns: [customer_id, product_type, shipping_region, orders, gross_sales, net_sales, total_sales, ordered_item_quantity]
Index: []

customer_id               product_type shipping_region  orders  \
0  5.440000e+12  Maternity and Nursing Top         Haryana       1   
1  5.730000e+12                   Baby Oil         Haryana       1   
3  5.730000e+12       Baby Anti-Slip Socks         Haryana       1   
5  5.770000e+12  Maternity and Nursing Top   Uttar Pradesh       1   
7  5.770000e+12             Twinning Combo     Maharashtra       1   

   gross_sales  net_sales  total_sales  ordered_item_quantity  
0      1439.83    1123.07      1325.22                      1  
1       422.03     379.83       448.20                      1  
3       677.12     609.41       719.10                      1  
5      1524.58    1524.58      1799.00                      1  
7      1355.08    1219.58      1439.10                      1

In [47]:
def convert_sqft_to_num(x):
    tokens = x.split('-')
    if len(tokens) ==2:
        return (float(tokens[0])+float(tokens[1]))/2
    try:
        return float(x)
    except:
        return None

In [49]:
convert_sqft_to_num('1325-1799')

1562.0

In [50]:
#now tp apply it to whole dataset, we will make a new dataframe and apply the function to it.

df4 = df3.copy() #it will copy the whole data of df3 to df4
df4['total_sales'] = df4['total_sales'].apply(convert_sqft_to_num)
df4.head(5)

AttributeError: 'float' object has no attribute 'split'