In [4]:
import numpy as np
a = np.array([5,6,9])
a[0]
a.ndim

1

In [3]:
a[1]

6

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [4]:
a = np.array([5,6,9])
a.ndim

1

In [5]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim


2

In [6]:
a.itemsize

4

In [7]:
a.dtype

dtype('int32')

In [8]:
a = np.array([[1,2],[3,4],[5,6]],dtype = np.float64)

In [9]:
a.itemsize

8

In [10]:
a.size

6

In [11]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [12]:
a.shape

(3, 2)

In [13]:
a = np.array([[1,2],[3,4],[5,6]], dtype = complex)

In [14]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
l = range(5)

In [19]:
l

range(0, 5)

In [20]:
l[0]

0

In [21]:
l[1]

1

In [22]:
np.arange(1,5)

array([1, 2, 3, 4])

In [24]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [25]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [26]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [27]:
a.shape

(3, 2)

In [28]:
a.reshape(2,3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [29]:
a.reshape(6,1)

array([[1.+0.j],
       [2.+0.j],
       [3.+0.j],
       [4.+0.j],
       [5.+0.j],
       [6.+0.j]])

In [30]:
a.ravel()

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [31]:
#mathematical functions

a.min()

(1+0j)

In [32]:
a.max()

(6+0j)

In [33]:
a.sum()

(21+0j)

In [34]:
a.sum(axis=0) #colums wise sum

array([ 9.+0.j, 12.+0.j])

In [35]:
a.sum(axis=1) #row wise sum

array([ 3.+0.j,  7.+0.j, 11.+0.j])

In [37]:
np.sqrt(a)

array([[1.        +0.j, 1.41421356+0.j],
       [1.73205081+0.j, 2.        +0.j],
       [2.23606798+0.j, 2.44948974+0.j]])

In [38]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [39]:
np.std(a)

1.707825127659933

In [42]:
#mathematical operations
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])           

In [43]:
a

array([[1, 2],
       [3, 4]])

In [44]:
b

array([[5, 6],
       [7, 8]])

In [45]:
a+b

array([[ 6,  8],
       [10, 12]])

In [46]:
a*b

array([[ 5, 12],
       [21, 32]])

In [47]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [48]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [ ]:
#indexing,slicing,iterating,stacking     left